[versions]
library = "1.1.0"
kotlin = "1.8.0"

[libraries]

[plugins]
kotlin-compose = "org.jetbrains.compose:1.3.0"
android-application = "com.android.application:7.3.0"
android-library = "com.android.library:7.3.0"
