[versions]
library = "1.1.0"

[libraries]

[plugins]
kotlin-miltiplatform = "org.jetbrains.kotlin.multiplatform:1.8.0"
android = "com.android.application:7.3.0"
kotlin-compose = "org.jetbrains.compose:1.3.0"
